# Generated by Django 5.1 on 2024-09-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210805_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='News',
            new_name='news',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='imgs/'),
        ),
    ]
